/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Case: typeof import('./src/components/Case.vue')['default']
    GlobalCase: typeof import('./src/components/GlobalCase.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestCases: typeof import('./src/components/TestCases.vue')['default']
    ToggleTheme: typeof import('./src/components/ToggleTheme.vue')['default']
  }
}
