/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Case: typeof import('./../components/Case.vue')['default']
    Chart: typeof import('./../components/Chart.vue')['default']
    GlobalCase: typeof import('./../components/GlobalCase.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestCases: typeof import('./../components/TestCases.vue')['default']
    ToggleTheme: typeof import('./../components/ToggleTheme.vue')['default']
  }
}
